dist: trusty
sudo: false

language: generic

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - latexmk
    - cm-super
    - pgf
    - texlive-bibtex-extra
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-lang-german
    - texlive-latex-recommended
    - texlive-latex-extra

script:
- bash make.sh

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: $TRAVIS_BUILD_DIR/padc.pdf
  skip_cleanup: true
  on:
    tags: true
